// <auto-generated />
namespace Vidly_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modify_cusmoer_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_cusmoer_name));
        
        string IMigrationMetadata.Id
        {
            get { return "202110040915216_modify_cusmoer_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
