// <auto-generated />
namespace Vidly_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class upbirth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upbirth));
        
        string IMigrationMetadata.Id
        {
            get { return "202110190525220_up-birth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
