// <auto-generated />
namespace Vidly_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial_mode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_mode));
        
        string IMigrationMetadata.Id
        {
            get { return "202110080715462_initial_mode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
