// <auto-generated />
namespace Vidly_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ubd_birth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ubd_birth));
        
        string IMigrationMetadata.Id
        {
            get { return "202110100910447_ubd_birth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
